services:
  postgresql:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
